/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BrowserRouteImport } from './routes/browser'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SubmitRouteImport } from './routes/submit'
import { Route as ApiAiOverviewRouteImport } from './routes/api/ai-overview'
import { Route as ApiCrossiAiRouteImport } from './routes/api/crossi-ai'
import { Route as ApiPublicSearchRouteImport } from './routes/api/public/search'
import { Route as ApiPublicSubmitRouteImport } from './routes/api/public/submit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowserRoute = BrowserRouteImport.update({
  id: '/browser',
  path: '/browser',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmitRoute = SubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiOverviewRoute = ApiAiOverviewRouteImport.update({
  id: '/api/ai-overview',
  path: '/api/ai-overview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCrossiAiRoute = ApiCrossiAiRouteImport.update({
  id: '/api/crossi-ai',
  path: '/api/crossi-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSearchRoute = ApiPublicSearchRouteImport.update({
  id: '/api/public/search',
  path: '/api/public/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSubmitRoute = ApiPublicSubmitRouteImport.update({
  id: '/api/public/submit',
  path: '/api/public/submit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/browser': typeof BrowserRoute
  '/dashboard': typeof DashboardRoute
  '/docs': typeof DocsRoute
  '/search': typeof SearchRoute
  '/submit': typeof SubmitRoute
  '/api/ai-overview': typeof ApiAiOverviewRoute
  '/api/crossi-ai': typeof ApiCrossiAiRoute
  '/api/public/search': typeof ApiPublicSearchRoute
  '/api/public/submit': typeof ApiPublicSubmitRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/browser': typeof BrowserRoute
  '/dashboard': typeof DashboardRoute
  '/docs': typeof DocsRoute
  '/search': typeof SearchRoute
  '/submit': typeof SubmitRoute
  '/api/ai-overview': typeof ApiAiOverviewRoute
  '/api/crossi-ai': typeof ApiCrossiAiRoute
  '/api/public/search': typeof ApiPublicSearchRoute
  '/api/public/submit': typeof ApiPublicSubmitRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/browser': typeof BrowserRoute
  '/dashboard': typeof DashboardRoute
  '/docs': typeof DocsRoute
  '/search': typeof SearchRoute
  '/submit': typeof SubmitRoute
  '/api/ai-overview': typeof ApiAiOverviewRoute
  '/api/crossi-ai': typeof ApiCrossiAiRoute
  '/api/public/search': typeof ApiPublicSearchRoute
  '/api/public/submit': typeof ApiPublicSubmitRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/browser'
    | '/dashboard'
    | '/docs'
    | '/search'
    | '/submit'
    | '/api/ai-overview'
    | '/api/crossi-ai'
    | '/api/public/search'
    | '/api/public/submit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/browser'
    | '/dashboard'
    | '/docs'
    | '/search'
    | '/submit'
    | '/api/ai-overview'
    | '/api/crossi-ai'
    | '/api/public/search'
    | '/api/public/submit'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/browser'
    | '/dashboard'
    | '/docs'
    | '/search'
    | '/submit'
    | '/api/ai-overview'
    | '/api/crossi-ai'
    | '/api/public/search'
    | '/api/public/submit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  BrowserRoute: typeof BrowserRoute
  DashboardRoute: typeof DashboardRoute
  DocsRoute: typeof DocsRoute
  SearchRoute: typeof SearchRoute
  SubmitRoute: typeof SubmitRoute
  ApiAiOverviewRoute: typeof ApiAiOverviewRoute
  ApiCrossiAiRoute: typeof ApiCrossiAiRoute
  ApiPublicSearchRoute: typeof ApiPublicSearchRoute
  ApiPublicSubmitRoute: typeof ApiPublicSubmitRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browser': {
      id: '/browser'
      path: '/browser'
      fullPath: '/browser'
      preLoaderRoute: typeof BrowserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submit': {
      id: '/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof SubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-overview': {
      id: '/api/ai-overview'
      path: '/api/ai-overview'
      fullPath: '/api/ai-overview'
      preLoaderRoute: typeof ApiAiOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/crossi-ai': {
      id: '/api/crossi-ai'
      path: '/api/crossi-ai'
      fullPath: '/api/crossi-ai'
      preLoaderRoute: typeof ApiCrossiAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/search': {
      id: '/api/public/search'
      path: '/api/public/search'
      fullPath: '/api/public/search'
      preLoaderRoute: typeof ApiPublicSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/submit': {
      id: '/api/public/submit'
      path: '/api/public/submit'
      fullPath: '/api/public/submit'
      preLoaderRoute: typeof ApiPublicSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  BrowserRoute: BrowserRoute,
  DashboardRoute: DashboardRoute,
  DocsRoute: DocsRoute,
  SearchRoute: SearchRoute,
  SubmitRoute: SubmitRoute,
  ApiAiOverviewRoute: ApiAiOverviewRoute,
  ApiCrossiAiRoute: ApiCrossiAiRoute,
  ApiPublicSearchRoute: ApiPublicSearchRoute,
  ApiPublicSubmitRoute: ApiPublicSubmitRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
